version: '3.7'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: 'grafana'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    container_name: 'nginx'
    volumes:
    #  - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    #  - "./etc/ssl:/etc/ssl"
    #  - "./web:/var/www/html"
    #  - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    environment:
      - NGINX_HOST=0.0.0.0
    # command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon of$
    # restart: always
