global:
  scrape_interval: '5s'
  evaluation_interval: '5s'
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /prometheus/metrics/
    static_configs:
    - targets: ['<host IP address>:80']
  - job_name: 'openweather'
    metrics_path: /metrics/
    static_configs:
    - targets: ['<host IP address>:80']
