global:
  scrape_interval: '5s'
  evaluation_interval: '5s'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['0.0.0.0:9090']
  - job_name: 'openweather'
    static_configs:
    - targets: ['172.19.0.1:5000']
  #- job_name: 'grafana'
  #  static_configs:
  #  - targets: ['0.0.0.0:3000']
