apiVersion: 1

deleteDatasources:
  - name: 'Prometheus'
    orgId: 1

datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    access: 'browser'
    orgId: 1
    url: 'http://<host IP address>:80/prometheus/'
    isDefault: true
    version: 1
    editable: false
